const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const str=(v:unknown)=>typeof v==="string"?v.trim():String(v??"").trim();
const content=(v:any):string=>{if(typeof v==="string")return v.trim();if(Array.isArray(v))return v.map(x=>typeof x==="string"?x:(x?.text||x?.content||"")).join("\n").trim();if(v&&typeof v==="object")return str(v.text||v.content);return ""};
async function user(req:Request){const h=req.headers.get("Authorization")||"";if(!/^bearer\s/i.test(h))return null;const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SB_PUBLISHABLE_KEY");if(!u||!k)return null;const r=await fetch(`${u}/auth/v1/user`,{headers:{Authorization:h,apikey:k}});return r.ok?await r.json():null;}
async function approved(id:string){const u=Deno.env.get("SUPABASE_URL"),k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!u||!k)return null;const r=await fetch(`${u}/rest/v1/advocate_registrations?select=id,advocate_name&auth_user_id=eq.${encodeURIComponent(id)}&status=eq.Approved&verification_status=eq.Approved&limit=1`,{headers:{apikey:k,Authorization:`Bearer ${k}`}});if(!r.ok)return null;const a=await r.json();return Array.isArray(a)&&a[0]?a[0]:null;}
async function call(key:string,model:string,messages:any[],maxTokens:number){for(let attempt=0;attempt<2;attempt++){const c=new AbortController();const t=setTimeout(()=>c.abort(),22000);try{const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","HTTP-Referer":"https://instantlegalservices.in/","X-Title":"Instant Legal Services"},body:JSON.stringify({model,messages,temperature:0.1,max_tokens:maxTokens,provider:{allow_fallbacks:true,sort:"throughput"}}),signal:c.signal});const raw=await r.text();let j:any=null;try{j=JSON.parse(raw)}catch{};if(r.ok)return {ok:true,status:r.status,j,error:""};const err=j?.error?.message||raw.slice(0,500);if((r.status===429||r.status>=500)&&attempt===0){await new Promise(x=>setTimeout(x,700));continue}return {ok:false,status:r.status,j,error:err};}catch(e:any){if(attempt===0){await new Promise(x=>setTimeout(x,400));continue}return {ok:false,status:e?.name==="AbortError"?504:502,j:null,error:e?.name==="AbortError"?"upstream timeout":e?.message||"upstream connection failed"};}finally{clearTimeout(t);}}return {ok:false,status:502,j:null,error:"upstream failure"};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return json({ok:true});if(req.method!=="POST")return json({ok:false,reply:"Method not allowed."},405);try{const b=await req.json();const mode=str(b?.mode||"public").toLowerCase();let adv:any=null;if(mode==="advocate"||mode==="research"){const u=await user(req);if(!u?.id)return json({ok:false,code:"AUTH_REQUIRED",reply:"Advocate login is required for Research AI."},401);adv=await approved(u.id);if(!adv)return json({ok:false,code:"ADVOCATE_ONLY",reply:"Advocate Research AI is available only to approved ILS Network advocates."},403);if(b?.action==="check")return json({ok:true,approved:true,advocate:{id:adv.id,name:adv.advocate_name}});}
const q=str(b?.question||b?.prompt);if(!q)return json({ok:false,reply:"Question is required."},400);if(q.length>12000)return json({ok:false,reply:"Question is too long."},400);const key=Deno.env.get("OPENROUTER_API_KEY");if(!key)return json({ok:false,code:"AI_NOT_CONFIGURED",reply:"AI service is not configured."},503);const isAdv=mode==="advocate"||mode==="research";const system=isAdv?`You are Instant Legal Services Advocate Research AI for approved Indian advocates. Give structured, careful Indian legal research. Never invent cases, citations, sections, dates or quotations. Distinguish verified law from matters requiring verification. Cover Issues, Applicable Law, Authorities, Application to Facts, Opponent/Prosecution Position, Best Supported Defence/Counter-Arguments, Procedure, Risks/Adverse Authorities and Verification Checklist. Never guarantee an outcome.`:`You are Instant Legal Services Public Legal Information AI for Indian law. Give concise, accurate general legal information. Never invent cases, citations, sections, dates or quotations. Distinguish BNS/BNSS/BSA from IPC/CrPC/IEA where relevant. Say when current primary-source verification is needed. Never guarantee an outcome.`;let prompt=isAdv?`Advocate research question:\n${q}`:`Indian legal information question:\n${q}`;const doc=str(b?.document_text);if(isAdv&&doc)prompt+=`\n\nCASE DOCUMENT (${str(b?.document_name)||"uploaded document"}):\n${doc.slice(0,50000)}\nTreat allegations as allegations unless the document records an admission or finding.`;const messages=[{role:"system",content:system},{role:"user",content:prompt}];
// First try OpenRouter's managed free router. It automatically selects an available free endpoint.
// Then use explicit free models as deterministic fallbacks. This avoids depending on one provider/model.
const models=["openrouter/free","google/gemma-4-31b-it:free","google/gemma-4-26b-a4b-it:free","openai/gpt-oss-20b:free"];const failures:any[]=[];for(const m of models){const r=await call(key,m,messages,isAdv?3000:1400);if(r.ok){const answer=content(r.j?.choices?.[0]?.message?.content);if(answer)return json({ok:true,verified:false,reply:answer,answer,sources:[],model:r.j?.model||m,mode,advocate:adv?{id:adv.id,name:adv.advocate_name}:undefined});}failures.push({model:m,status:r.status,error:String(r.error||"provider failure").slice(0,240)});}
console.error("AI_PROVIDER_FAILURE",JSON.stringify(failures));return json({ok:false,code:"AI_PROVIDER_UNAVAILABLE",reply:"AI service is temporarily unavailable. Please try again shortly."},503);}catch(e:any){console.error("AI_SERVICE_FATAL",e);return json({ok:false,code:"AI_SERVICE_ERROR",reply:"AI service error. Please try again."},500);}});