import { createClient } from "jsr:@supabase/supabase-js@2";
import * as pdfjsLib from "npm:pdfjs-dist@4.10.38/legacy/build/pdf.mjs";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const SCI="https://www.sci.gov.in/",FETCH_MS=20000,MAX_DISCOVER=20,MAX_PROCESS=1,MAX_PDF_CANDIDATES=8;
const HEADERS={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36","Accept":"text/html,application/xhtml+xml,application/pdf,*/*","Accept-Language":"en-US,en;q=0.9","Referer":SCI};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"Content-Type":"application/json"}});
async function fetchT(url:string,init:RequestInit={},ms=FETCH_MS){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal,redirect:"follow"});}finally{clearTimeout(t)}}
async function hash(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function clean(s:unknown){return String(s??"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#8217;/g,"'").replace(/&#x27;/gi,"'").replace(/\s+/g," ").trim()}
function parseDate(v:string){const m=v.match(/(\d{1,2})-([A-Za-z]{3})-(\d{4})/);if(!m)return null;const mo:any={Jan:"01",Feb:"02",Mar:"03",Apr:"04",May:"05",Jun:"06",Jul:"07",Aug:"08",Sep:"09",Oct:"10",Nov:"11",Dec:"12"};return mo[m[2]]?`${m[3]}-${mo[m[2]]}-${m[1].padStart(2,"0")}`:null}
function pdfFromText(v:string){const diary=v.match(/Diary Number\s*[:\-]?\s*([0-9]+)/i),d=v.match(/(\d{1,2})-([A-Za-z]{3})-(\d{4})/);if(!diary||!d)return null;const date=parseDate(d[0]);return date?`${SCI}sci-get-pdf/?diary_no=${encodeURIComponent(diary[1])}&type=j&order_date=${encodeURIComponent(date)}&from=latest_judgements_order`:null}
function isOfficial(url:string){try{const u=new URL(url);return u.protocol==="https:"&&(u.hostname==="www.sci.gov.in"||u.hostname==="sci.gov.in")}catch{return false}}
function decodeHtml(v:string){return v.replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&#x27;/gi,"'").replace(/&nbsp;/gi," ")}
function extractPdfCandidates(html:string,baseUrl:string){const out:string[]=[];const add=(raw:string)=>{try{const u=new URL(decodeHtml(raw),baseUrl);if(!isOfficial(u.href))return;const s=u.href.toLowerCase();if(/\.pdf(?:[?#]|$)/i.test(s)||/sci-get-pdf|download.*pdf|view-pdf/i.test(s)){if(!out.includes(u.href))out.push(u.href)}}catch{}};const attr=/\b(?:href|src|data-url|data-href)=["']([^"']+)["']/gi;let m:any;while((m=attr.exec(html))&&out.length<MAX_PDF_CANDIDATES)add(m[1]);const quoted=/(https?:[^"'\s<>]+)/gi;while((m=quoted.exec(html))&&out.length<MAX_PDF_CANDIDATES)add(m[1].replace(/\\\//g,"/"));return out}
async function fetchOfficialPdf(initialUrls:string[]){const tried:string[]=[],queue=[...initialUrls.filter(isOfficial)],seen=new Set<string>();while(queue.length&&tried.length<MAX_PDF_CANDIDATES){const url=queue.shift()!;if(seen.has(url))continue;seen.add(url);tried.push(url);try{const r=await fetchT(url,{headers:HEADERS});const ct=(r.headers.get("content-type")||"").toLowerCase(),finalUrl=r.url;if(!r.ok)continue;const bytes=new Uint8Array(await r.arrayBuffer()),sig=new TextDecoder().decode(bytes.slice(0,5));if(sig.startsWith("%PDF")&&bytes.byteLength>100)return {bytes,url:finalUrl,tried};if(ct.includes("application/pdf")&&bytes.byteLength>100)return {bytes,url:finalUrl,tried};const html=new TextDecoder().decode(bytes);for(const candidate of extractPdfCandidates(html,finalUrl))if(!seen.has(candidate)&&queue.length+tried.length<MAX_PDF_CANDIDATES)queue.push(candidate)}catch{}}throw Error(`Official PDF could not be retrieved; tried ${tried.length} official source URL(s)`)}
async function extractPdf(bytes:Uint8Array){const loadingTask=pdfjsLib.getDocument({data:bytes,disableWorker:true,useSystemFonts:true}),pdf=await loadingTask.promise,pages:string[]=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();pages.push(c.items.map((x:any)=>typeof x.str==="string"?x.str:"").join(" "))}return pages.join("\n\n").replace(/\s+/g," ").trim()}
async function processSummary(base:string,service:string,id:string){const r=await fetchT(`${base}/functions/v1/process-judgment-summary`,{method:"POST",headers:{Authorization:`Bearer ${service}`,apikey:service,"Content-Type":"application/json"},body:JSON.stringify({judgment_id:id})},30000);const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d={success:false,error:`invalid JSON: ${t.slice(0,500)}`}}return {httpStatus:r.status,data:d,raw:t}}
function retryDelay(attempt:number){return Math.min(360,Math.max(5,Math.pow(2,Math.min(attempt,6))*5))}
async function run(){const base=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!base||!service)throw Error("Supabase environment is not configured");const sup=createClient(base,service),counts:any={discovered:0,retained:0,pdf_retrieved:0,text_extracted:0,summarized:0,waiting:0,failed:0,repaired:0,duplicates_skipped:0,skipped_backoff:0,skipped_completed:0};let html="";try{const r=await fetchT(SCI,{headers:HEADERS});if(!r.ok)throw Error(`SCI returned ${r.status}`);html=await r.text()}catch{counts.failed++;return counts}
const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,found:any[]=[];let m:any;while((m=re.exec(html))&&found.length<MAX_DISCOVER){const label=clean(m[2]);if(!/Diary Number/i.test(label)||!(/\bVS\.?\b/i.test(label)))continue;const title=clean(label.split(" - ")[0]).replace(/^[*•]+/g,"").trim();if(title.length<5)continue;const date=parseDate(label),cn=(label.match(/(?:C\.A\.|Crl\.A\.|SLP\(C\)|SLP\(Crl\)|W\.P\.\(C\)|T\.P\.\(C\)|M\.A\.)[^-]*?(?=\s*-\s*Diary Number|$)/i)||[])[0]?.trim()||null,pdf=pdfFromText(label);if(!pdf)continue;found.push({case_title:title,case_number:cn,judgment_date:date,court_name:"Supreme Court of India",court_type:"Supreme Court",official_source_url:new URL(m[1],SCI).href,source_pdf_url:pdf,source_domain:"sci.gov.in"})}counts.discovered=found.length;
for(const j of found){try{const h=await hash([j.court_name,j.case_title,j.case_number||"",j.judgment_date||""].join("|")),{data:ex,error:exErr}=await sup.from("judgments").select("id,source_pdf_url,official_source_url").eq("source_hash",h).maybeSingle();if(exErr)throw exErr;if(ex){counts.duplicates_skipped++;const upd:any={};if(j.source_pdf_url&&ex.source_pdf_url!==j.source_pdf_url)upd.source_pdf_url=j.source_pdf_url;if(j.official_source_url&&ex.official_source_url!==j.official_source_url)upd.official_source_url=j.official_source_url;if(Object.keys(upd).length){await sup.from("judgments").update(upd).eq("id",ex.id);counts.repaired++}continue}const {error}=await sup.from("judgments").insert({case_title:j.case_title,case_number:j.case_number,judgment_date:j.judgment_date,court_name:j.court_name,court_type:j.court_type,official_source_url:j.official_source_url,source_pdf_url:j.source_pdf_url,source_domain:j.source_domain,source_hash:h,is_latest:true,is_verified:true,summary_status:"pending",judgment_text_status:"pending",primary_category:"Uncategorized",short_summary:"Judgment identified from the official Supreme Court of India source; document processing is pending."});if(error)throw error;counts.retained++}catch{counts.failed++}}
// v14: include processing jobs in the admission pool so in-progress chunks can always resume.
// EGRESS-SAFE: do not pull large judgment/document text into the scheduler queue.\n// The selected fields are metadata only; full text is fetched only by the summary worker when needed.\nconst {data:pool,error:poolError}=await sup.from("judgments").select("id,case_title,case_number,judgment_date,created_at,summary_status,summary_generated_at,judgment_text_status,source_pdf_url,official_source_url,processing_error").in("summary_status",["pending","failed","processing"]).order("judgment_date",{ascending:false}).order("created_at",{ascending:false}).limit(50);if(poolError)throw poolError;
const ids=(pool||[]).map((x:any)=>x.id);let jobs:any[]=[];if(ids.length){const {data:jd,error:je}=await sup.from("judgment_summary_jobs").select("judgment_id,status,next_chunk,total_chunks,retry_count,next_retry_at,last_error,updated_at").in("judgment_id",ids);if(je)throw je;jobs=jd||[]}
const jm=new Map(jobs.map((x:any)=>[x.judgment_id,x]));const now=Date.now();const eligible=(pool||[]).filter((j:any)=>{if(j.summary_status==="completed"){counts.skipped_completed++;return false}const job=jm.get(j.id);if(job?.status==="waiting"&&job.next_retry_at&&new Date(job.next_retry_at).getTime()>now)return false;return true});
const rank=(j:any)=>{const job=jm.get(j.id);if(job){if(job.status==="waiting"&&job.next_retry_at&&new Date(job.next_retry_at).getTime()<=now)return 0;if(job.status==="processing"||job.status==="ready")return 1;return 1}if(j.judgment_text_status==="completed")return 2;if(j.source_pdf_url||j.official_source_url)return 3;return 4};
eligible.sort((a:any,b:any)=>{const ra=rank(a),rb=rank(b);if(ra!==rb)return ra-rb;const ja=jm.get(a.id),jb=jm.get(b.id);if(ra===1){const ca=Number(ja?.next_chunk||0),cb=Number(jb?.next_chunk||0);if(ca!==cb)return cb-ca;}return new Date(b.judgment_date||0).getTime()-new Date(a.judgment_date||0).getTime()||new Date(b.created_at||0).getTime()-new Date(a.created_at||0).getTime();});
const queue=eligible.slice(0,MAX_PROCESS);
for(const j of queue){try{
const {data:fresh,error:fe}=await sup.from("judgments").select("id,summary_status,summary_generated_at,judgment_text_status,source_pdf_url,official_source_url").eq("id",j.id).maybeSingle();if(fe)throw fe;if(!fresh)continue;if(fresh.summary_status==="completed"){counts.skipped_completed++;continue}
const {data:fj,error:fje}=await sup.from("judgment_summary_jobs").select("status,retry_count,next_retry_at").eq("judgment_id",j.id).maybeSingle();if(fje)throw fje;if(fj?.status==="waiting"&&fj.next_retry_at&&new Date(fj.next_retry_at).getTime()>Date.now()){counts.skipped_backoff++;continue}
if(fresh.judgment_text_status!=="completed"){const got=await fetchOfficialPdf([String(fresh.source_pdf_url||"").trim(),String(fresh.official_source_url||"").trim()].filter(Boolean));const text=await extractPdf(got.bytes);if(text.length<200)throw Error("Extracted PDF text is too short");const ts=new Date().toISOString();const {error}=await sup.from("judgments").update({source_pdf_url:got.url,document_text:text,judgment_text:text,document_retrieved_at:ts,judgment_text_status:"completed",judgment_text_extracted_at:ts,processing_error:null,summary_status:"pending",updated_at:ts}).eq("id",j.id);if(error)throw error;counts.pdf_retrieved++;counts.text_extracted++}
const result=await processSummary(base,service,j.id),d=result.data||{};
const {data:after,error:ae}=await sup.from("judgments").select("summary_status,summary_generated_at").eq("id",j.id).maybeSingle();if(ae)throw ae;
if(after?.summary_status==="completed"&&after.summary_generated_at){counts.summarized++;continue}
if(result.httpStatus>=200&&result.httpStatus<300&&d.success){if(d.status==="waiting"){const attempt=Number(fj?.retry_count||0)+1,mins=retryDelay(attempt),ts=new Date(Date.now()+mins*60000).toISOString();await sup.from("judgments").update({summary_status:"pending",processing_error:d.error||"AI provider temporarily unavailable; automatic retry scheduled.",updated_at:new Date().toISOString()}).eq("id",j.id);await sup.from("judgment_summary_jobs").update({retry_count:attempt,next_retry_at:ts,last_error:d.error||"waiting",status:"waiting",updated_at:new Date().toISOString()}).eq("judgment_id",j.id);counts.waiting++}else{counts.summarized++}}else{const err=String(d.error||result.raw||`summary ${result.httpStatus}`),rateLimited=result.httpStatus===429||/429|rate.?limit|too many requests|temporarily unavailable|quota/i.test(err),attempt=Number(fj?.retry_count||0)+1,mins=retryDelay(attempt),ts=new Date(Date.now()+mins*60000).toISOString();await sup.from("judgments").update({summary_status:rateLimited?"pending":"failed",processing_error:err.slice(0,2000),updated_at:new Date().toISOString()}).eq("id",j.id);await sup.from("judgment_summary_jobs").update({retry_count:attempt,next_retry_at:ts,last_error:err.slice(0,2000),status:"waiting",updated_at:new Date().toISOString()}).eq("judgment_id",j.id);rateLimited?counts.waiting++:counts.failed++}
}catch(e){const err=String(e),{data:jr}=await sup.from("judgment_summary_jobs").select("retry_count").eq("judgment_id",j.id).maybeSingle(),attempt=Number(jr?.retry_count||0)+1,mins=retryDelay(attempt),ts=new Date(Date.now()+mins*60000).toISOString();counts.failed++;await sup.from("judgments").update({summary_status:"pending",processing_error:err.slice(0,2000),updated_at:new Date().toISOString()}).eq("id",j.id);await sup.from("judgment_summary_jobs").update({retry_count:attempt,next_retry_at:ts,last_error:err.slice(0,2000),status:"waiting",updated_at:new Date().toISOString()}).eq("judgment_id",j.id)}}
return counts}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({success:false,error:"Use POST"},405);try{return json({success:true,counts:await run(),cost_policy:"PRIMARY_MODEL_WITH_FREE_FALLBACK",automation:"retry_backoff",pdf_engine:"pdfjs-npm-disableWorker",version:"v14"})}catch(e){console.error("daily-judgment-pipeline",e);return json({success:false,error:String(e)},500)}});
