import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const e=(k:string)=>Deno.env.get(k)||""; const url=e("SUPABASE_URL"), role=e("SUPABASE_SERVICE_ROLE_KEY"), kid=e("RAZORPAY_KEY_ID"), secret=e("RAZORPAY_KEY_SECRET");
async function hmac(s:string,m:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(s),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const b=await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(m));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(!url||!role||!kid||!secret)return json({ok:false,error:"PAYMENT_GATEWAY_NOT_CONFIGURED"},503);const auth=req.headers.get("Authorization")||"";const sb=createClient(url,role,{global:{headers:{Authorization:auth}}});const {data:{user}}=await sb.auth.getUser();if(!user)return json({ok:false,error:"AUTH_REQUIRED"},401);let b:any;try{b=await req.json()}catch{return json({ok:false,error:"INVALID_JSON"},400)};
if(b.action==="create"){const oid=String(b.order_id||"");if(!oid)return json({ok:false,error:"ORDER_ID_REQUIRED"},400);const {data:o}=await sb.from("orders").select("id,order_number,total,currency,status,user_id").eq("id",oid).eq("user_id",user.id).maybeSingle();if(!o)return json({ok:false,error:"ORDER_NOT_FOUND"},404);if(o.status!=="pending")return json({ok:false,error:"ORDER_NOT_PAYABLE"},409);const {data:ex}=await sb.from("payments").select("id,gateway_order_id,status").eq("order_id",oid).eq("status","created").order("created_at",{ascending:false}).limit(1).maybeSingle();if(ex?.gateway_order_id)return json({ok:true,key_id:kid,razorpay_order_id:ex.gateway_order_id,payment_id:ex.id,amount:Number(o.total),currency:o.currency});const r=await fetch("https://api.razorpay.com/v1/orders",{method:"POST",headers:{Authorization:"Basic "+btoa(`${kid}:${secret}`),"Content-Type":"application/json"},body:JSON.stringify({amount:Math.round(Number(o.total)*100),currency:o.currency,receipt:o.order_number,notes:{ils_order_id:o.id,user_id:user.id},payment_capture:1})});const rp=await r.json();if(!r.ok||!rp?.id)return json({ok:false,error:"RAZORPAY_ORDER_CREATE_FAILED"},502);const {data:p,error:pe}=await sb.from("payments").insert({order_id:oid,gateway:"razorpay",gateway_order_id:rp.id,amount:Number(o.total),currency:o.currency,status:"created"}).select("id").single();if(pe)return json({ok:false,error:"PAYMENT_RECORD_FAILED"},500);return json({ok:true,key_id:kid,razorpay_order_id:rp.id,payment_id:p.id,amount:Number(o.total),currency:o.currency});}
if(b.action==="verify"){const oid=String(b.order_id||""),pid=String(b.razorpay_payment_id||""),sig=String(b.razorpay_signature||"");if(!oid||!pid||!sig)return json({ok:false,error:"PAYMENT_FIELDS_REQUIRED"},400);const {data:o}=await sb.from("orders").select("id,order_number,status,user_id,service_request_id").eq("id",oid).eq("user_id",user.id).maybeSingle();if(!o)return json({ok:false,error:"ORDER_NOT_FOUND"},404);const {data:p}=await sb.from("payments").select("id,gateway_order_id,status").eq("order_id",oid).eq("gateway","razorpay").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!p)return json({ok:false,error:"PAYMENT_RECORD_NOT_FOUND"},404);if(p.status==="paid")return json({ok:true,status:"paid",already_processed:true});const expected=await hmac(secret,`${p.gateway_order_id}|${pid}`);if(expected!==sig)return json({ok:false,error:"SIGNATURE_VERIFICATION_FAILED"},400);await sb.from("payments").update({gateway_payment_id:pid,status:"paid",paid_at:new Date().toISOString()}).eq("id",p.id);await sb.from("orders").update({status:"paid"}).eq("id",oid);if(o.service_request_id){await sb.from("service_requests").update({status:"paid"}).eq("id",o.service_request_id);const {data:sr}=await sb.from("service_requests").select("service_id").eq("id",o.service_request_id).maybeSingle();if(sr?.service_id)await sb.from("entitlements").upsert({user_id:user.id,service_id:sr.service_id,order_id:oid,status:"active"},{onConflict:"user_id,service_id,order_id"});}return json({ok:true,status:"paid",order_number:o.order_number});}
return json({ok:false,error:"UNKNOWN_ACTION"},400)});